travis:
  secure:
    BINSTAR_TOKEN: oTVqkzSCd0dY3/oJxt35qTrwmeb1J/7TIl3It6mx1TdRJ7FKlhNuhMi7NUaNuWKBJsqSEyzImlOxsSi8/GWVA2juEQLuU6JWT5GKyMa9Z+akjKf+796UBfcTA/BvObL0DMyzON905nRdM1qedTSWDNu5VNPWDFgc38jDdvBgF+fkoSaeEL7xXPt1sKJUwgxHVonJQBaFrLFnq+q265aNFZH0zKLaUVqFjmZMWg7uX9IhzdjlrpDnxfjNGwtwneAaI8j5Kmj0icugji9u2hhSsYkXe1EA0LNuQi10QXTbI6JgAf7Gh+KSc7xmho2PyKveDhMq8c06HXPLCge/T5srgXScbcFXW3aYUbUavazfntLgaNiI+Us8pi//91PNHESfBWFoKyZBhPp1aF4quW/iIbGqJHlMLphoCTsPuFUgam6WN+VVryCEGfOWenFI6nUyJUfuG9TSPbsMiBLyCudqfmq2cv78Vvw/0I4DhaHoZLiLdBwso2gXifITrHx6+Oenj6I64Qpv5DeNFQiR8OPw9gWzfmCYVukqP44BUYtfa+/VNYczV7ThhpVshFYQ9DSZDUwsKcyj7tVApVA+KpTglufJ6S0O6v4E7Mdhv8/+NLGGWhNBqG8jBPtxahws20tBDvIlTfm3XlnP3TDXZmcf3udAy3594QSGEldIQn4vyyU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
