travis:
  secure:
    BINSTAR_TOKEN: efSbhcQW8bZArTM90Edx5EJtHmZ6EciBmxIXkS+Hn58wpzXsGbJE2ZIhiZQAZZe/ZeaoWkwrmHfMYYEl7W527OeSyDztFmKBKqRZX6IVe2xnKcM26rjJWZJheid7WfgkBzi6R3z0/HFnO2rJoXxnViQFRj25bHVg+kGt27l3umlBaSyENGRRrMxE9goUb8Lqe0RT+YZvTjGcEItp8YY5nYYNjm4LQLYP9Z6aqFryS3M+XCNHghv7FelTgtcNITLVlhtxBaJmjf8NhZ1bAd16vEP2XjAVU4V9mTbc+T37Zu9KX77YjsfSwLYrSNWK1fzcbl6Da0CRtLAMPFjk2x0+ANkxEucPlQlLLU6+NfH8C6i6eN2P8hCaTmmp84sh9M7w3Q48MP5PkH0LHl4TeBfHWi3XDPxHuz+JvXT+b4tOT86YHwvr/pngnIXKGj2apMDcE8xqN7/gMAbPPx7uMPyLPq3OzV+coCrEIE8Xjt44C+9yagEONN0V+ZJ69jaKAe+0ppiN9uVX64cNknIsrXnLBqKJc3iegJ8Cl4U4NqEyUNmutIHeEmQpVQH54GK7XIoCNkpDiU/U+D0U2ICTOl/ZlCUudNONS800nCNXEcUtqKdXE6qSkcwh7o2GVHuDjV5kWvGIuEM5Vg2AlSGGUg/1BT7xUk07Xx7Qtd4ITH8ZvIE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
